export enum UserRoleEnum {
  AGP_LEADERSHIP = 'AGP_LEADERSHIP',
  AGP_APPRENTICES = 'AGP_APPRENTICES',
  GD_LEADERSHIP = 'GD_LEADERSHIP',
  MNT_LEADERSHIP = 'MNT_LEADERSHIP',
  MNT_APPRENTICES = 'MNT_APPRENTICES',
  SECRETARIAT = 'SECRETARIAT',
  AGP_LESSONS = 'AGP_LESSONS',
  EBD_TEACHERS = 'EBD_TEACHERS',
  AE_VOLUNTEER = 'AE_VOLUNTEER',
  PASTORAL_TEAM = 'PASTORAL_TEAM',
  ADMIN = 'ADMIN',
}
